### ISSUE TITLE
SingleDateandtimepicer inside dialog not working

### ISSUE THREAD

**Issue by azzahrah** [florent37/SingleDateAndTimePicker#113]
01-07 05:35:13.546 10850-10850/com.centratelemedia.gpstracker E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.centratelemedia.gpstracker, PID: 10850
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getHeight()' on a null object reference
                                                                                    at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$2.run(BottomSheetHelper.java:91)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:160)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
01-07 05:35:13.696 959-988/? E/WindowManager: Window AppOp is -1 Window Package iscom.centratelemedia.gpstracker
01-07 05:35:14.336 10925-10925/com.centratelemedia.gpstracker E/Process: android_os_Process_getProcessNameByPid pid is 10925
01-07 05:35:14.336 10925-10925/com.centratelemedia.gpstracker E/Process: android_os_Process_getProcessNameByPid value is edia.gpstracker
01-07 05:35:14.966 959-1907/? E/WindowManager: Window AppOp is -1 Window Package iscom.centratelemedia.gpstracker

**Comment by driftingPixel** [comment]
We use in our project DialogFragment and then we haven't problems with it.

**Comment by phuquy2114** [comment]
Some of me
