### ISSUE TITLE
intValue() null when using DoubleDateAndTimePickerDialog

### ISSUE THREAD

**Issue by setanallas** [florent37/SingleDateAndTimePicker#115]
i try to use DoubleDateAndTimePickerDialog and following the instruction from readme and i got this error
<pre>
<code>
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                     at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.getTabsListDrawable(DoubleDateAndTimePickerDialog.java:234)
                                                                     at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.init(DoubleDateAndTimePickerDialog.java:145)
                                                                     at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.access$000(DoubleDateAndTimePickerDialog.java:25)
                                                                     at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog$1.onLoaded(DoubleDateAndTimePickerDialog.java:62)
                                                                     at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:73)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                     
</code></pre>

im writing this in my onCreate at mainActivity.java
<pre><code>
new DoubleDateAndTimePickerDialog.Builder(this)
                //.bottomSheet()
                //.curved()
                //.minutesStep(15)
                .title("Double")
                .tab0Text("Depart")
                .tab1Text("Return")
                .listener(new DoubleDateAndTimePickerDialog.Listener() {
                    @Override
                    public void onDateSelected(List<Date> dates) {

                    }
                }).display();
</code></pre>
any one can help?

**Comment by jasperlittle** [comment]
Explicitly setting the background color with:
```
new DoubleDateAndTimePickerDialog.Builder(this)
        .backgroundColor(Color.WHITE)
```
seems to fix this issue. I may take a look at this fixing the default behavior over the weekend if no one else wants it

**Comment by setanallas** [comment]
great its work for me
thanks mr @jasperlittle
