### ISSUE TITLE
App is crashing when i try to inflate the widget.

### ISSUE THREAD

**Issue by harikesh59** [florent37/SingleDateAndTimePicker#149]
`06-26 20:06:24.359 27400-27400/co.chiron.agent.chironagent E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.chiron.agent.chironagent, PID: 27400
    android.view.InflateException: Binary XML file line #55: Binary XML file line #55: Error inflating class com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:44)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5571)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: android.view.InflateException: Binary XML file line #55: Error inflating class com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker
        at android.view.LayoutInflater.createView(LayoutInflater.java:649)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:44) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:623)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:44) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
     Caused by: android.view.InflateException: Binary XML file line #75: Binary XML file line #75: Error inflating class com.github.florent37.singledateandtimepicker.widget.WheelYearPicker
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:19830)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:102)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:93)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:44) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
     Caused by: android.view.InflateException: Binary XML file line #75: Error inflating class com.github.florent37.singledateandtimepicker.widget.WheelYearPicker
        at android.view.LayoutInflater.createView(LayoutInflater.java:649)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.view.View.inflate(View.java:19830) 
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:102) 
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:93) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:44) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:623)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.view.View.inflate(View.java:19830) 
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:102) 
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:93) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:44) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
     Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'Y'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
        at com.github.florent37.singledateandtimepicker.widget.WheelYearPicker.init(WheelYearPicker.java:33)
        at com.github.florent37.singledateandtimepicker.widget.WheelPicker.<init>(WheelPicker.java:175)
        at com.github.florent37.singledateandtimepicker.widget.WheelYearPicker.<init>(WheelYearPicker.java:28)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.view.View.inflate(View.java:19830) 
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:102) 
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.<init>(SingleDateAndTimePicker.java:93) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:768) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:44) 
        at android.os.Handler.handleCallback(Handler.java:742) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5571) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
`

**Comment by GhulamAkber** [comment]
i am also facing the same issue.
Does anyone know how to solve it?

**Comment by jjere** [comment]
Most likely due to getCurrentLocal() method in WheelPicker.
Seems it crashes for API 23. Is that the api you have?

**Comment by nukc** [comment]
```java
Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'Y'
    at java.text.SimpleDateFormat.null validatePatternCharacter(null)(SimpleDateFormat.java:314)
    at java.text.SimpleDateFormat.null validatePattern(null)(SimpleDateFormat.java:303)
    at java.text.SimpleDateFormat.null <init>(null)(SimpleDateFormat.java:356)
    at com.github.florent37.singledateandtimepicker.widget.WheelYearPicker.null b(null)(WheelYearPicker.java)
    at com.github.florent37.singledateandtimepicker.widget.WheelPicker.null <init>(null)(WheelPicker.java)
    at com.github.florent37.singledateandtimepicker.widget.WheelYearPicker.null <init>(null)(WheelYearPicker.java)
    ... 36 more
```

```java
simpleDateFormat = new SimpleDateFormat("YYYY", getCurrentLocale());
```
pattern not support 'Y'?

**Comment by kishanverma26** [comment]
getting same issue
