### ISSUE TITLE
Crash when setting custom today text in xml

### ISSUE THREAD

**Issue by klisiewicz** [florent37/SingleDateAndTimePicker#167]
`
<com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker
        android:id="@+id/datePicker"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:picker_curved="true"
        app:picker_cyclic="false"
        app:picker_displayDays="true"
        app:picker_displayHours="false"
        app:picker_displayMinutes="false"
        app:picker_displayMonthNumbers="false"
        app:picker_displayYears="true"
        **app:picker_todayText="@string/l_today"**
        app:picker_visibleItemCount="7" />
`

`
java.lang.ArrayIndexOutOfBoundsException: length=364; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.github.florent37.singledateandtimepicker.widget.WheelPicker.setDefaultDate(WheelPicker.java:256)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setDefaultDate(SingleDateAndTimePicker.java:459)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.onAttachedToWindow(SingleDateAndTimePicker.java:218)
        at android.view.View.dispatchAttachedToWindow(View.java:17445)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1668)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by pedromassango** [comment]
Getting this issue too

**Comment by mice777** [comment]
Also when setting `app:picker_todayText=... ` in layout, it crashes other way.
WheelDayPicker.convertItemToDate string-compares to own today string and fails silently if today string can't be converted to Date. 

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
        at java.util.Calendar.setTime(Calendar.java:1749)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.getDate(SingleDateAndTimePicker.java:428)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.updateDaysOfMonth(SingleDateAndTimePicker.java:499)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setDefaultDate(SingleDateAndTimePicker.java:466)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.onAttachedToWindow(SingleDateAndTimePicker.java:221)
```

**Comment by Luuk99** [comment]
Has this been solved? I have the same problem, now all text is in Dutch using a Locale except for 'today'.

**Comment by pedromassango** [comment]
I changed the text via strings.xml you need to clone the code then add it in your project as an module, then make your changes and import it to your main project. It worked for me!

**Comment by Luuk99** [comment]
Thanks for the speedy response! Would that create a problem if I want to use multiple languages? I eventually want my user to be able to choose between English and Dutch

**Comment by pedromassango** [comment]
Nope. I will work fine
