### ISSUE TITLE
I dont know why i am getting this issue.

### ISSUE THREAD

**Issue by kashish0391** [florent37/SingleDateAndTimePicker#17]
FATAL EXCEPTION: main
                  Process: com.zalonstyle.app.zalonstaff, PID: 21319
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getHeight()' on a null object reference
                      at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$2.run(BottomSheetHelper.java:93)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5441)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by techartist** [comment]
I think we need to see more of your code.

**Comment by rogercastaneda** [comment]
hi @techartist i created a empty project in my account (https://github.com/rogercastaneda/datetimesamplebug). 
I put 3 comments to show you when and how it works for me when i add this library to a empty project.
Can you check please the mainActivity? I'm getting the same error as @kashish0391 
Thanks

**Comment by neosarchizo** [comment]
I got this error too. I found why it happend. Because of [this line](https://github.com/florent37/SingleDateAndTimePicker/blob/bbcb6c1d99fd64eef4cd4998c16bc6908c225dfd/singledateandtimepicker/src/main/java/com/github/florent37/singledateandtimepicker/dialog/BottomSheetHelper.java#L40)
Maybe you passed a context which is not an activity.

**Comment by alparslandev** [comment]
Can this library work with Dialog Fragments? 
My code is this 
`new SingleDateAndTimePickerDialog.Builder(getContext())
                        .curved()
                        .minutesStep(30)
                        .title(App.str(R.string.date))
                        .display();`
In Dialog Fragment if I use this code, your dialog stays behind of Dialog Fragment.

**Comment by IriscShih** [comment]
@alparslandev Have you already figured out a way to not have this timepicker dialog stays behind a Dialog Fragment?

**Comment by honeykapoor7** [comment]
can you share the code for it @alparslandev

**Comment by alparslandev** [comment]
No I can't. Are you kidding me? It's been 3 years and 2 companies. Thanks for nothing.
Edit: These are very very late answers. I removed my star from this library. Thanks for reminding
Edit 2: as you see, I shared my code. What code do you want. I am very angry now.
