### ISSUE TITLE
February month not showing

### ISSUE THREAD

**Issue by Usama75** [florent37/SingleDateAndTimePicker#197]
Today date is 30/1/2019. florent37SingleDateAndTimePicker not showing February, showing March two times.

**Comment by thereisonlywe** [comment]
Having problem with the Arabic language. Crashing like this:

```
 java.lang.IndexOutOfBoundsException: Invalid index 30, size is 28
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
        at java.util.ArrayList.get(ArrayList.java:304)
        at com.github.florent37.singledateandtimepicker.widget.WheelPicker.setDefaultDate(WheelPicker.java:256)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setDefaultDate(SingleDateAndTimePicker.java:469)
```
