### ISSUE TITLE
29 of february

### ISSUE THREAD

**Issue by oxanakorabl** [florent37/SingleDateAndTimePicker#199]
i have problems with 29.02.2000: can choose it, but if i set this date as default got this

  Caused by: java.lang.IndexOutOfBoundsException: Index: 28, Size: 28
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.github.florent37.singledateandtimepicker.widget.WheelPicker.setDefaultDate(WheelPicker.java:256)

**Comment by supriya-ski** [comment]
Is this issue fixed? I am unable to select 29 Feb 2020.

**Comment by Amaranadh1** [comment]
Shall you provide complete source code of SingleDateAndTimePicker with Today and Tomorrow text? Thanks In Advance.
