### ISSUE TITLE
setTodayText crashes app

### ISSUE THREAD

**Issue by mice777** [florent37/SingleDateAndTimePicker#235]
No matter where I put call to `setTodayText`, app crashes:

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
        at java.util.Calendar.setTime(Calendar.java:1749)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.getDate(SingleDateAndTimePicker.java:428)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.updateDaysOfMonth(SingleDateAndTimePicker.java:499)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setDefaultDate(SingleDateAndTimePicker.java:466)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.onAttachedToWindow(SingleDateAndTimePicker.java:221)
        at android.view.View.dispatchAttachedToWindow(View.java:18571)
```

All I want is change english "Today" to localized version. This seems like impossible.

**Comment by AgungLaksana** [comment]
same problem here, after setTodayText, then when I scroll the widget to today or before, then it will crash
