### ISSUE TITLE
crash in my

### ISSUE THREAD

**Issue by 593361260** [florent37/SingleDateAndTimePicker#236]

**Comment by 593361260** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.TimeZone.getOffset(long)' on a null object reference
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2285)
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2254)
        at java.util.Calendar.complete(Calendar.java:1543)
        at java.util.GregorianCalendar.add(GregorianCalendar.java:897)
        at com.github.florent37.singledateandtimepicker.widget.WheelDayPicker.generateAdapterValues(WheelDayPicker.java:74)
        at com.github.florent37.singledateandtimepicker.widget.WheelPicker.<init>(WheelPicker.java:182)
        at com.github.florent37.singledateandtimepicker.widget.WheelDayPicker.<init>(WheelDayPicker.java:34)

**Comment by Vidhyadharan24** [comment]
The app is crashing because the DateHelper.getTimeZone() method is returning a null object when no time zone is set, setting the default TimeZone in DateHelper.setTimeZone(TimeZone timeZone) method via the TimeZone.getDefault() resolved the issue.
