### ISSUE TITLE
crash when 31st is selected

### ISSUE THREAD

**Issue by dimabran** [florent37/SingleDateAndTimePicker#238]
Whenever 31st of a month is selected the app crashes
`java.lang.IndexOutOfBoundsException: Index: 30, Size: 30
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.github.florent37.singledateandtimepicker.widget.WheelPicker.setDefaultDate(WheelPicker.java:260)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setDefaultDate(SingleDateAndTimePicker.java:477)
        at com.github.florent37.singledateandtimepicker.dialog.SingleDateAndTimePickerDialog.init(SingleDateAndTimePickerDialog.java:166)
        at com.github.florent37.singledateandtimepicker.dialog.SingleDateAndTimePickerDialog.access$000(SingleDateAndTimePickerDialog.java:23)
        at com.github.florent37.singledateandtimepicker.dialog.SingleDateAndTimePickerDialog$1.onLoaded(SingleDateAndTimePickerDialog.java:56)
        at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1$2.onPreDraw(BottomSheetHelper.java:78)`

any fix for it?

**Comment by LvWind** [comment]
check this PR
https://github.com/florent37/SingleDateAndTimePicker/pull/212

**Comment by momadthenomad** [comment]
If this is fixed, the issue should be closed.
