### ISSUE TITLE
NPE when initialize doubleDateAndTimePickerDailog

### ISSUE THREAD

**Issue by mhdfazil** [florent37/SingleDateAndTimePicker#286]
Code: 
`new DoubleDateAndTimePickerDialog.Builder(this)
                .bottomSheet()
                .curved() .title("Double")
                .tab0Text("Depart")
                .tab1Text("Return").display() ;`

Error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setTimeZone(java.util.TimeZone)' on a null object reference
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.setTimeZone(DoubleDateAndTimePickerDialog.java:427)
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.access$700(DoubleDateAndTimePickerDialog.java:30)
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog$Builder.build(DoubleDateAndTimePickerDialog.java:736)
        at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog$Builder.display(DoubleDateAndTimePickerDialog.java:755)`

**Comment by Adi-n-tech** [comment]
simply update library in latest version 2.2.8 it will work
