### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by abdulatif1707** [florent37/SingleDateAndTimePicker#3]
java.lang.IllegalArgumentException: View=android.widget.FrameLayout{aa82bfd G.E...C.. ......ID 0,0-1440,2476 #7f0e00a8 app:id/bottom_sheet_background} not attached to window manager
                                                                         at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
                                                                         at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:377)
                                                                         at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:135)
                                                                         at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper.remove(BottomSheetHelper.java:129)
                                                                         at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper.access$500(BottomSheetHelper.java:18)
                                                                         at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$3$1.onAnimationEnd(BottomSheetHelper.java:120)
                                                                         at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                         at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                         at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7331)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by subnetz** [comment]
abdulatif1707 could you test if this problem still exists?
Should be fixed with commit f6e75b8
