### ISSUE TITLE
Unable to add window. Permission denied for this window type 

### ISSUE THREAD

**Issue by tombcato** [florent37/SingleDateAndTimePicker#4]
@florent37

**Comment by tombcato** [comment]
Process: com.github.florent37.sample.singledateandtimepicker, PID: 29755
 android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3c199f2 -- permission denied for this window type
     at android.view.ViewRootImpl.setView(ViewRootImpl.java:603)
     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)
     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
     at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:64)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5438)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by florent37** [comment]
mmmm ok I will investigate it, thanks

**Comment by spidfire** [comment]
Was fixed by updating to 1.1.15 (not sure which update exactly, but thanks)
