### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by jseparovic** [florent37/SingleDateAndTimePicker#41]
Getting:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.getTabsListDrawable(DoubleDateAndTimePickerDialog.java:200)
at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.init(DoubleDateAndTimePickerDialog.java:130)
at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.access$000(DoubleDateAndTimePickerDialog.java:24)
at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog$1.onLoaded(DoubleDateAndTimePickerDialog.java:55)
at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:73)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

When trying to load inside a Fragment textView onClick Listener:

```
public void onClick(View v) {
    final Calendar calendar = Calendar.getInstance();
    calendar.set(Calendar.DAY_OF_MONTH, 1);
    calendar.set(Calendar.MONTH, 0);
    calendar.set(Calendar.YEAR, 2017);
    final Date minDate = calendar.getTime();
    calendar.set(Calendar.DAY_OF_MONTH, 5);
    final Date maxDate = calendar.getTime();

    DoubleDateAndTimePickerDialog.Builder doubleBuilder = new DoubleDateAndTimePickerDialog.Builder(getContext())
        //.bottomSheet()
        //.curved()
        //.backgroundColor(Color.BLACK)
        //.mainColor(Color.GREEN)
        .minutesStep(15)
        .mustBeOnFuture()
        .minDateRange(minDate)
        .maxDateRange(maxDate)
        .tab0Text("Start")
        .tab1Text("End")
        .listener(new DoubleDateAndTimePickerDialog.Listener() {
            @Override
            public void onDateSelected(List<Date> dates) {
                tvStartValue.setText(parseDate(dates.get(0)));
                tvFinishValue.setText(parseDate(dates.get(1)));
            }
        }
    );
    doubleBuilder.display();
}
```

**Comment by jseparovic** [comment]
Just realized backgroundColor and mainColor is mandatory. This error disappears when setting them:
```
        .backgroundColor(Color.BLACK)
        .mainColor(Color.GREEN)
```
