### ISSUE TITLE
DoubleDateAndTimePickerDialog demo doesn't work

### ISSUE THREAD

**Issue by martinvano** [florent37/SingleDateAndTimePicker#56]
If I copy paste the code from readme to my app, it crashes. If I uncomment the bottomSheet() line, it crashes on the different place since the view is not in the layout.

```
new SingleDateAndTimePickerDialog.Builder(context)
            //.bottomSheet()
            //.curved()
            //.minutesStep(15)
            
            //.displayHours(false)
            //.displayMinutes(false)
            
            .title("Simple")
            .listener(new SingleDateAndTimePickerDialog.Listener() {
                @Override
                public void onDateSelected(Date date) {
                    
                }
            }).display();
```
Here is the stack trace
```

                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.getTabsListDrawable(DoubleDateAndTimePickerDialog.java:226)
                                                                at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.init(DoubleDateAndTimePickerDialog.java:139)
                                                                at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog.access$000(DoubleDateAndTimePickerDialog.java:25)
                                                                at com.github.florent37.singledateandtimepicker.dialog.DoubleDateAndTimePickerDialog$1.onLoaded(DoubleDateAndTimePickerDialog.java:60)
                                                                at com.github.florent37.singledateandtimepicker.dialog.BottomSheetHelper$1.run(BottomSheetHelper.java:73)
                                                                at android.os.Handler.handleCallback(Handler.java:769)
                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                at android.os.Looper.loop(Looper.java:164)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by florent37** [comment]
try the 1.1.5 ;)
